define([
  "nablarch/ui/Widget"
, "nablarch/ui/Collapsible"
, "nablarch/ui/event"
, "nablarch/ui/LightBox"
, "nablarch/ui/readonly"
, "nablarch/ui/selector"
, "nablarch/ui/TreeMenu"
, "nablarch/ui/ContextMenu"
, "nablarch/ui"
, "nablarch/util/BigDecimal"
, "nablarch/util/Consumer"
, "nablarch/util/DateUtil"
, "nablarch/util/SimpleDateFormat"
, "nablarch/util"
], function(Widget) { "use strict"; return { Widget: Widget }; });
